### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/spreadsheet-ecology-lesson#268]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by hoytpr** [comment]
I definitely want to hit the release date, although I've been slammed with real life lately. Count me in for testing.

**Comment by ErinBecker** [comment]
Hi @cbahlai, @tracykteal, and @hoytpr - Just confirming that you're still planning on including your lesson in the June 2019 release. We'll be putting out a blog post tomorrow inviting contributors to work on issues that have been tagged as part of the release milestone, so if there are specific issues you're looking for community help with, please add them to that milestone.

**Comment by tracykteal** [comment]
Thanks, yes, we still have to go through the review checklist. But overall I think the lesson is already in pretty good shape, so we're planning to be a part of the release.

**Comment by tracykteal** [comment]
@cbahlai @hoytpr I can do a pass through of the checklist next week.

**Comment by ErinBecker** [comment]
Sounds excellent. Thank you for confirming @tracykteal!

**Comment by hoytpr** [comment]
I'm planning to go through this also.

**Comment by cbahlai** [comment]
I'll also see what I can do this afternoon!

**Comment by cbahlai** [comment]
I've read through and here's what I've got- I didn't want to check above in case I missed something
- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [ ] A schedule appears on the lesson homepage (e.g. not “00:00”) 
 *shouldn't the start of the lesson be 00:00?*
- [ ] Each episode includes learning objectives
*phrased as 'objectives' not 'learning objectives'*
- [x] Each episode includes questions
- [x] Each episode includes key points
- [ ] Setup instructions are up-to-date, correct, clear, and complete
 *good on my windows 10 enterprise machine*
- [ ] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
 *nothing standing out*
- [x] Some Instructor notes are provided
- [ ] Lesson links work as expected
*did not check all*

**Comment by ErinBecker** [comment]
Thanks @cbahlai! To answer your question about the schedule, the intention is that the schedule not be 00:00 all the way through. This would only happen on lessons where the teaching and exercise sections of the episode headers were all set to 0. You can go ahead and check this one off for your lesson.

**Comment by ErinBecker** [comment]
Hey Maintainers - just checking in to see if you're still planning on joining the release this month. We're asking that all lessons have completed the checklist by [Tuesday, 4 June, Anywhere on Earth time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20190604T235959&p1=3399) in order to be included in the release. Please let me and @fmichonneau know if you have any questions or are running into any technical issues with preparing your lesson.

**Comment by hoytpr** [comment]
Erin,
YES. I'll go through the entire lesson today. Don't expect any problems.

**Comment by ErinBecker** [comment]
Thanks @hoytpr. Sounds great!

**Comment by tracykteal** [comment]
Thanks @cbahlai for going through all of this! 

- Confirming that 'Objectives' is fine to use instead of 'Learning Objectives', since that's what's in the template, so checking that off. 
- File structure also looks good to me, so checking that off. 
- Download of data and installation of LibreOffice worked on MacOS Mojave. So, I think fine to check that off.

**Comment by tracykteal** [comment]
- Checked the links in all the episodes and all the top level menu items. So, looks like all links work. Checking that off.

**Comment by tracykteal** [comment]
@hoytpr if there's anything else you want to check on Setup, we can do that. If that looks good to you, then you can check that last thing off. Thanks @hoytpr and @cbahlai!

**Comment by hoytpr** [comment]
@tracykteal @fmichonneau @cbahlai @ErinBecker 
The setup  was no problem at all. Libre Office installed perfectly on Windows 10, and the file download links worked. I am going to check off setup and am comfortable with this lesson to go live.`

**Comment by ErinBecker** [comment]
Awesome work @cbahlai @tracykteal @hoytpr and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3260731

**Comment by tracykteal** [comment]
Woo hoo! Thank you @fmichonneau!

**Comment by hoytpr** [comment]
Excellent work @fmichonneau  and everybody.

**Comment by cbahlai** [comment]
+100 Yay!
